"""Generates the frontend's bundled data module from the seed.

``frontend/assets/data.js`` used to be maintained by hand, which is how a
regex rewriting it once produced ``1e-06e-06`` and broke the module at parse
time. It is now emitted from the same seed the API serves, so the static
fallback and the API cannot disagree about what was measured.

Usage: ``python -m app.seed.export_frontend``
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
SEED_PATH = Path(__file__).resolve().parent / "v3" / "problems.json"
OUTPUT_PATH = REPO_ROOT / "frontend" / "assets" / "data.js"


def _js(value: Any) -> str:
    """Render a Python value as JavaScript.

    Numbers go through ``repr`` rather than JSON so a small cost stays a plain
    decimal: JSON would emit 1e-06, and a previous hand-edit of this file
    mangled exactly that into an unparseable literal.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, float):
        text = f"{value:.10f}".rstrip("0").rstrip(".")
        return text or "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value).replace("'", "\\u0027")
    raise TypeError(f"Cannot render {type(value)!r} as JavaScript")


def _obj(pairs: dict[str, Any], indent: str) -> str:
    body = ", ".join(f"{key}: {_js(value)}" for key, value in pairs.items())
    return "{ " + body + " }"


def _audit(payload: dict[str, Any] | None) -> str:
    if not payload:
        return "null"
    fields = {
        "majorityLabel": payload["majority_label"],
        "majorityBaselineAccuracy": payload["majority_baseline_accuracy"],
        "chanceAccuracy": payload["chance_accuracy"],
        "trainSize": payload["train_size"],
        "testSize": payload["test_size"],
        "contaminationRate": payload["contamination_rate"],
    }
    provenance = payload.get("term_provenance")
    rendered = _obj(fields, "")
    if provenance:
        terms = _obj(
            {
                "totalTerms": provenance["total_terms"],
                "attestedTerms": provenance["attested_terms"],
                "unattestedTerms": provenance["unattested_terms"],
                "accuracyAllTerms": provenance["accuracy_all_terms"],
                "accuracyAttestedOnly": provenance["accuracy_attested_only"],
                "accuracyUnattestedOnly": provenance["accuracy_unattested_only"],
            },
            "",
        )
        rendered = rendered[:-2] + f", termProvenance: {terms} }}"
    return rendered


def render() -> str:
    seed = json.loads(SEED_PATH.read_text(encoding="utf-8"))
    lines = [
        "// Generated by `python -m app.seed.export_frontend`. Do not edit by hand.",
        "//",
        "// This is the copy the site falls back to when no backend is reachable.",
        "// It is emitted from the same seed the API serves, so the two cannot",
        "// disagree about what has been measured.",
        "",
        "export const benchmarkProblems = [",
    ]

    for problem in seed["problems"]:
        dataset = problem["dataset"]
        lines.append("  {")
        for key, value in (
            ("slug", problem["slug"]),
            ("title", problem["title"]),
            ("category", problem["category"]),
            ("description", problem["description"]),
            ("decisionQuestion", problem["decision_question"]),
            ("datasetLabel", dataset.get("name")),
            ("datasetSize", dataset.get("sample_count_label")),
            ("datasetLicense", dataset.get("license")),
            ("datasetProvenance", dataset.get("provenance_notes")),
            ("status", problem["status"]),
            ("rationale", problem["rationale"]),
        ):
            lines.append(f"    {key}: {_js(value)},")

        requirements = problem["default_requirements"]
        lines.append(
            "    requirements: "
            + _obj(
                {
                    "minAccuracy": requirements["min_accuracy"],
                    "maxLatencyMs": requirements["max_latency_ms"],
                    "auditabilityRequired": requirements["auditability_required"],
                    "monthlyVolume": requirements["monthly_volume"],
                },
                "",
            )
            + ","
        )

        lines.append("    results: [")
        for method in problem["methods"]:
            result = method["result"]
            fields = _obj(
                {
                    "id": method["method_id"],
                    "name": method["name"],
                    "shortName": method["short_name"],
                    "kind": method["method_class"],
                    "accuracy": result["accuracy"],
                    "costPer1k": result["cost_per_1k"],
                    "latencyMs": result["latency_p50_ms"],
                    "deterministic": result["deterministic"],
                    "auditable": result["auditable"],
                    "complexityRank": method["complexity_rank"],
                    "resultState": result["result_state"],
                    "costState": result["cost_state"],
                    "sampleCount": result["sample_count"],
                    "notes": method["notes"],
                },
                "",
            )
            audit = _audit(result.get("leakage_audit"))
            lines.append(f"      {fields[:-2]}, audit: {audit} }},")
        lines.append("    ],")
        lines.append("  },")

    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUTPUT_PATH.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
