"""initial schema

Revision ID: 0fb23d4a1d51
Revises:
Create Date: 2026-08-30 17:01:03.780356

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fb23d4a1d51"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("decision_question", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("benchmark_definition_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("problem", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_problem_slug"), ["slug"], unique=True)

    op.create_table(
        "dataset_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("sample_count_label", sa.String(length=80), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("license", sa.String(length=120), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("provenance_notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "method",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("stable_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=80), nullable=False),
        sa.Column("method_class", sa.String(length=40), nullable=False),
        sa.Column("complexity_rank", sa.Integer(), nullable=False),
        sa.Column("implementation_version", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=True),
        sa.Column("model_version", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("problem_id", "stable_key", name="uq_method_problem_key"),
    )
    with op.batch_alter_table("method", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_method_stable_key"), ["stable_key"], unique=False)

    op.create_table(
        "requirement_profile",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("min_accuracy", sa.Float(), nullable=False),
        sa.Column("max_latency_ms", sa.Integer(), nullable=False),
        sa.Column("auditability_required", sa.Boolean(), nullable=False),
        sa.Column("monthly_volume", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("problem_id", "name", name="uq_profile_problem_name"),
    )
    op.create_table(
        "benchmark_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("method_id", sa.String(length=36), nullable=False),
        sa.Column("code_commit_sha", sa.String(length=40), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("environment_json", sa.Text(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_version.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["method_id"], ["method.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "result",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("method_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=200), nullable=True),
        sa.Column("result_state", sa.String(length=16), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("task_success_rate", sa.Float(), nullable=True),
        sa.Column("latency_p50_ms", sa.Float(), nullable=False),
        sa.Column("latency_p95_ms", sa.Float(), nullable=True),
        sa.Column("cost_per_1k", sa.Float(), nullable=False),
        sa.Column("deterministic", sa.Boolean(), nullable=False),
        sa.Column("auditable", sa.Boolean(), nullable=False),
        sa.Column("metric_definition_version", sa.String(length=32), nullable=False),
        sa.Column("raw_artifact_uri", sa.String(length=500), nullable=True),
        sa.Column("measured_at", sa.DateTime(), nullable=True),
        sa.Column("cost_state", sa.String(length=16), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["method_id"], ["method.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("method_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("result")
    op.drop_table("benchmark_run")
    op.drop_table("requirement_profile")
    with op.batch_alter_table("method", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_method_stable_key"))

    op.drop_table("method")
    op.drop_table("dataset_version")
    with op.batch_alter_table("problem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_problem_slug"))

    op.drop_table("problem")
    # ### end Alembic commands ###
