"""record the leakage audit and allow unrun methods

Revision ID: 3e03d63e2256
Revises: 0fb23d4a1d51
Create Date: 2026-08-30 19:20:50.016242

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e03d63e2256"
down_revision: str | Sequence[str] | None = "0fb23d4a1d51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("result", schema=None) as batch_op:
        batch_op.add_column(sa.Column("leakage_audit_json", sa.Text(), nullable=True))
        batch_op.alter_column(
            "metric_definition_version", existing_type=sa.VARCHAR(length=32), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("result", schema=None) as batch_op:
        batch_op.alter_column(
            "metric_definition_version", existing_type=sa.VARCHAR(length=32), nullable=False
        )
        batch_op.drop_column("leakage_audit_json")

    # ### end Alembic commands ###
